package main

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/eavalenzuela/eyeexam/internal/config"
	"github.com/eavalenzuela/eyeexam/internal/store"
)

func newInitCmd() *cobra.Command {
	var (
		engagement string
		force      bool
	)
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold config, audit key, and SQLite database",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfgDir := config.ConfigDir()
			dataDir := config.DataDir()
			if err := os.MkdirAll(cfgDir, 0o700); err != nil {
				return err
			}
			if err := os.MkdirAll(dataDir, 0o700); err != nil {
				return err
			}

			cfgPath := filepath.Join(cfgDir, "config.yaml")
			if _, err := os.Stat(cfgPath); err == nil && !force {
				return fmt.Errorf("config already exists at %s (use --force to overwrite)", cfgPath)
			}

			keyPath := filepath.Join(cfgDir, "audit.key")
			if err := writeAuditKeyIfAbsent(keyPath, force); err != nil {
				return err
			}

			scaffold := defaultConfigYAML(engagement, dataDir, keyPath)
			if err := os.WriteFile(cfgPath, []byte(scaffold), 0o600); err != nil {
				return err
			}

			// Apply migrations to create the DB.
			dbPath := filepath.Join(dataDir, "eyeexam.db")
			s, err := store.Open(context.Background(), dbPath)
			if err != nil {
				return fmt.Errorf("open store: %w", err)
			}
			_ = s.Close()

			fmt.Println("initialized eyeexam:")
			fmt.Println("  config:     ", cfgPath)
			fmt.Println("  audit key:  ", keyPath)
			fmt.Println("  database:   ", dbPath)
			fmt.Println("  builtin pack: embedded in binary (no path needed)")
			fmt.Println()
			fmt.Println("next:")
			fmt.Println("  eyeexam pack list")
			fmt.Println("  eyeexam plan --pack builtin --hosts localhost")
			return nil
		},
	}
	cmd.Flags().StringVar(&engagement, "engagement", "HOMELAB-DEFAULT",
		"engagement id to write into the scaffold")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite an existing config / audit key")
	return cmd
}

func writeAuditKeyIfAbsent(path string, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		return nil // keep existing
	}
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return err
	}
	privBytes, err := encodePrivKey(priv)
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, privBytes, 0o600); err != nil {
		return err
	}
	pubBytes := pem.EncodeToMemory(&pem.Block{
		Type:  "EYEEXAM AUDIT PUBLIC KEY",
		Bytes: pub,
	})
	if err := os.WriteFile(path+".pub", pubBytes, 0o644); err != nil {
		return err
	}
	return nil
}

func encodePrivKey(priv ed25519.PrivateKey) ([]byte, error) {
	return pem.EncodeToMemory(&pem.Block{
		Type:  "EYEEXAM AUDIT PRIVATE KEY",
		Bytes: priv,
	}), nil
}

func defaultConfigYAML(engagementID, dataDir, keyPath string) string {
	return fmt.Sprintf(`# eyeexam config (generated by 'eyeexam init')
engagement:
  id: %s
  description: edit me

state:
  data_dir: %s
  database: eyeexam.db

audit:
  key_path: %s
  log_path: %s/audit.log

runner:
  local:
    enabled: true
  ssh:
    default_user: eyeexam
    connect_timeout: 10s
    command_timeout: 5m

# Additional packs are added via 'eyeexam pack add <name> <path>'. The
# binary-embedded "builtin" pack is always available; do not add a
# config entry for it.
# packs:
#   - name: my-attack-pack
#     path: ~/.local/share/eyeexam/packs/my-attack-pack
#     source: native

limits:
  global_tests_per_second: 1
  per_host_concurrency: 1

ui:
  listen: 127.0.0.1:8088
`, engagementID, dataDir, keyPath, dataDir)
}
